---
- name: Remove old Promtail binary and configuration
  file:
    path: /usr/local/bin/promtail-linux-amd64
    state: absent

- name: Download Promtail binary
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v2.4.1/promtail-linux-amd64.zip"
    dest: /usr/local/bin/promtail-linux-amd64.zip

- name: Unzip Promtail binary
  unarchive:
    src: /usr/local/bin/promtail-linux-amd64.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Set execute permission on Promtail binary
  file:
    path: /usr/local/bin/promtail-linux-amd64
    mode: '0755'

- name: Create Promtail configuration directory
  file:
    path: /etc/promtail
    state: directory

- name: Deploy Promtail configuration file
  template:
    src: promtail-config.j2
    dest: /etc/promtail/config-promtail.yaml
  notify: Restart Promtail service

- name: Deploy Promtail configuration file
  template:
    src: promtail-config.j2
    dest: /etc/promtail/config-promtail.yaml

- name: Create Promtail service file
  template:
    src: promtail-service.j2
    dest: /etc/systemd/system/promtail.service

- name: Start and enable Promtail service
  systemd:
    name: promtail
    enabled: yes
    state: started
